### ISSUE TITLE
/run/user/1000/gvfs

### ISSUE THREAD

**Issue by njmulsqb** [thatonetester/sumrecon#2]
Upon running the script I am having this response:
**find: ‘/run/user/1000/gvfs’: Permission denied
[-] Eyewitness required to run script**

I have installed Eyewitness, P.s when I run script with sudo, it gives me this response:
**[-] assetfinder required to run script
find: ‘/run/user/1000/gvfs’: Permission denied
[-] Eyewitness required to run script**

How can I run the script successfully?

**Comment by Gr1mmie** [comment]
I will look into this. What are you running the script on? the more information I have the better. I'll look into this as soon as I get the chance

**Comment by njmulsqb** [comment]
> I will look into this. What are you running the script on? the more information I have the better. I will look into this as soon as I get the chance

I am running it on my Kali linux machine (latest release)

**Comment by juanresendiz813** [comment]
I'm also using the latest kali and I just had this problem. What I did was change line 23:

if [ ! -x "$(find / -type f -name 'EyeWitness')" 

INTO

if [ ! -x "$(command -v eyewitness)"

AND line 165

echo "[+] Running eyewitness against all compiled domains..."
    eyewitness=$(find / -type f -name 'EyeWitness.py')
    python3 $eyewitness --web -f $url/recon/httprobe/alive.txt -d $url/recon/eyewitness --resolve --no-prompt

INTO

echo "[+] Running eyewitness against all compiled domains..."
    python3 /usr/share/eyewitness/EyeWitness.py
 --web -f $url/recon/httprobe/alive.txt -d $url/recon/eyewitness --resolve --no-prompt


It has something to do with running the find command and sudo at the same time. I hope it works for you if you haven't found it.

Oh Gr1mmie thanks for the script awesome work keep it up.

**Comment by juanresendiz813** [comment]
https://unix.stackexchange.com/questions/77453/why-cannot-find-read-run-user-1000-gvfs-even-though-it-is-running-as-root/77592#77592

**Comment by Gr1mmie** [comment]
Awesome job finding a fix @juanresendiz813 ! glad you're liking it :)

**Comment by njmulsqb** [comment]
Thanks a lot, @juanresendiz813. Your solution worked, that eyewitness command needed a fix. Thanks mate

**Comment by clipp3rX** [comment]
Permission denied. How could I solve this error?
![image](https://github.com/Gr1mmie/sumrecon/assets/112723215/7e838796-40b4-404b-a31f-1c54b60c19f8)
